### ISSUE TITLE
The POIs of chapter 3 are not seen in UEFN

### ISSUE THREAD

**Issue by Gianpi11111** [SenseiUsagi/umap-to-uefn-converter#13]
help me

**Comment by Its4Nik** [comment]
> help me
> 

@SenseiUsagi 
- [ ] add missing Points of intrrest

**Comment by SenseiUsagi** [comment]
@Gianpi11111
I will need a little bit more information that just that. Please provide more information on what should have happened and what did happen. Also try to use the issue templates in the future.

**Comment by Gianpi11111** [comment]
When I copy the ch3 txt file and paste it into UEFN you don't see the poi
![Unreal Editor 17_11_2024 19_16_21](https://github.com/user-attachments/assets/18bcb36f-28c0-4aca-ad45-c05c62471f0e)

**Comment by Gianpi11111** [comment]
Is it possible to add the functionality to make streaming grids?
![upgradedchapter3gridbyhades txt - Google Drive e altre 6 pagine - Profilo 2 - Microsoft​ Edge 29_11_2024 14_06_56](https://github.com/user-attachments/assets/36be552e-0a3c-4919-ad9f-5464b71ca8fd)

**Comment by SenseiUsagi** [comment]
@Gianpi11111 
Can you upload a few .json files of Ch3 POIs so I can debugg the problem?
Also streaming grids do work but you have to convert them one by one. See the "Levels inside level also converting" (#12) issue for more details.

**Comment by Gianpi11111** [comment]
grid

**Comment by SenseiUsagi** [comment]
@Gianpi11111 
That will sadly not be possible anytime soon, you will have to each grid sector one by one

**Comment by SenseiUsagi** [comment]
@Gianpi11111 
What do you mean?

**Comment by Its4Nik** [comment]
@Gianpi11111 

> help me create my app converter pls 

If you have any Problems please describe them in detail, we cannot help you if you dont provide any details.
Also requests like "help me" will likely be ignored since it is not possible to know for us what kind of problems you have.

Also we will not help you create your own converter since you seem to lack most of the conversion understanding as seen in a reply above.

So 2 options you either provide us some json files (as said before) or you describe your problem in detail... (not something like "help me it isnt working")


Thank you for understanding

**Comment by Gianpi11111** [comment]
[Artemis_Terrain_HLOD.json](https://github.com/user-attachments/files/17968560/Artemis_Terrain_HLOD.json)
[Artemis_Terrain_Grid_H8.json](https://github.com/user-attachments/files/17968562/Artemis_Terrain_Grid_H8.json)
[Artemis_Spline_Grid_D6.json](https://github.com/user-attachments/files/17968563/Artemis_Spline_Grid_D6.json)
[Artemis_Terrain_Grid_H2.json](https://github.com/user-attachments/files/17968564/Artemis_Terrain_Grid_H2.json)
[Artemis_Terrain_Grid_G7.json](https://github.com/user-attachments/files/17968565/Artemis_Terrain_Grid_G7.json)
[Artemis_Terrain_Grid_G2.json](https://github.com/user-attachments/files/17968566/Artemis_Terrain_Grid_G2.json)
[Artemis_Terrain_Grid_F6.json](https://github.com/user-attachments/files/17968567/Artemis_Terrain_Grid_F6.json)
[Artemis_Terrain_Grid_E3.json](https://github.com/user-attachments/files/17968568/Artemis_Terrain_Grid_E3.json)
[Artemis_Terrain_Grid_E1.json](https://github.com/user-attachments/files/17968569/Artemis_Terrain_Grid_E1.json)
[Artemis_Terrain_Grid_D6.json](https://github.com/user-attachments/files/17968570/Artemis_Terrain_Grid_D6.json)
[Artemis_Terrain_Grid_D3.json](https://github.com/user-attachments/files/17968572/Artemis_Terrain_Grid_D3.json)
[Artemis_Terrain_Grid_D2.json](https://github.com/user-attachments/files/17968573/Artemis_Terrain_Grid_D2.json)
[Artemis_Terrain_Grid_B8.json](https://github.com/user-attachments/files/17968574/Artemis_Terrain_Grid_B8.json)
[Artemis_Terrain_Grid_B7.json](https://github.com/user-attachments/files/17968575/Artemis_Terrain_Grid_B7.json)
[Artemis_Terrain_Grid_B5.json](https://github.com/user-attachments/files/17968576/Artemis_Terrain_Grid_B5.json)
[Artemis_Terrain_Grid_B4.json](https://github.com/user-attachments/files/17968577/Artemis_Terrain_Grid_B4.json)
[Artemis_Terrain_Grid_B1.json](https://github.com/user-attachments/files/17968578/Artemis_Terrain_Grid_B1.json)
[Artemis_Terrain_Grid_A5.json](https://github.com/user-attachments/files/17968579/Artemis_Terrain_Grid_A5.json)
[Artemis_POI_LobbyIsland_001.json](https://github.com/user-attachments/files/17968580/Artemis_POI_LobbyIsland_001.json)
[Artemis_Grid_Foundations.json](https://github.com/user-attachments/files/17968581/Artemis_Grid_Foundations.json)

**Comment by Its4Nik** [comment]
> [Artemis_Terrain_HLOD.json](https://github.com/user-attachments/files/17968560/Artemis_Terrain_HLOD.json)
> [Artemis_Terrain_Grid_H8.json](https://github.com/user-attachments/files/17968562/Artemis_Terrain_Grid_H8.json)
> [Artemis_Spline_Grid_D6.json](https://github.com/user-attachments/files/17968563/Artemis_Spline_Grid_D6.json)
> [Artemis_Terrain_Grid_H2.json](https://github.com/user-attachments/files/17968564/Artemis_Terrain_Grid_H2.json)
> [Artemis_Terrain_Grid_G7.json](https://github.com/user-attachments/files/17968565/Artemis_Terrain_Grid_G7.json)
> [Artemis_Terrain_Grid_G2.json](https://github.com/user-attachments/files/17968566/Artemis_Terrain_Grid_G2.json)
> [Artemis_Terrain_Grid_F6.json](https://github.com/user-attachments/files/17968567/Artemis_Terrain_Grid_F6.json)
> [Artemis_Terrain_Grid_E3.json](https://github.com/user-attachments/files/17968568/Artemis_Terrain_Grid_E3.json)
> [Artemis_Terrain_Grid_E1.json](https://github.com/user-attachments/files/17968569/Artemis_Terrain_Grid_E1.json)
> [Artemis_Terrain_Grid_D6.json](https://github.com/user-attachments/files/17968570/Artemis_Terrain_Grid_D6.json)
> [Artemis_Terrain_Grid_D3.json](https://github.com/user-attachments/files/17968572/Artemis_Terrain_Grid_D3.json)
> [Artemis_Terrain_Grid_D2.json](https://github.com/user-attachments/files/17968573/Artemis_Terrain_Grid_D2.json)
> [Artemis_Terrain_Grid_B8.json](https://github.com/user-attachments/files/17968574/Artemis_Terrain_Grid_B8.json)
> [Artemis_Terrain_Grid_B7.json](https://github.com/user-attachments/files/17968575/Artemis_Terrain_Grid_B7.json)
> [Artemis_Terrain_Grid_B5.json](https://github.com/user-attachments/files/17968576/Artemis_Terrain_Grid_B5.json)
> [Artemis_Terrain_Grid_B4.json](https://github.com/user-attachments/files/17968577/Artemis_Terrain_Grid_B4.json)
> [Artemis_Terrain_Grid_B1.json](https://github.com/user-attachments/files/17968578/Artemis_Terrain_Grid_B1.json)
> [Artemis_Terrain_Grid_A5.json](https://github.com/user-attachments/files/17968579/Artemis_Terrain_Grid_A5.json)
> [Artemis_POI_LobbyIsland_001.json](https://github.com/user-attachments/files/17968580/Artemis_POI_LobbyIsland_001.json)
> [Artemis_Grid_Foundations.json](https://github.com/user-attachments/files/17968581/Artemis_Grid_Foundations.json)
> 

Thank you we are going to take a look into it

**Comment by Gianpi11111** [comment]
if you want i have other json files of ch3 s1

**Comment by SenseiUsagi** [comment]
@Gianpi11111 
I have tested the .json files you have provided, I dont know what FModel you used to get them but your json files contain absurd location values. My converter technically does everything right, the map does get converter however most objects are so far out of bounds that the editor camera literally cant reach them.
![grafik](https://github.com/user-attachments/assets/9fc12389-f124-4198-8ab7-d8c118cf2c00)
![grafik](https://github.com/user-attachments/assets/5dcc7350-0c16-4605-b977-bfd1c818343b)

I suggest using a different version of FModel and try again. Other than that there is nothing I can do to help you
