### ISSUE TITLE
Add info about Layer 8 Problem after downloading

### ISSUE THREAD

**Issue by SenseiUsagi** [SenseiUsagi/umap-to-uefn-converter#7]
Add extra Info block in the help section about how you import converted maps into uefn (because layer 8 problem).
Something like:

"How do I get a converted map into UEFN?"
"You copy the content of the converted .txt and then in UEFN paste it (its recommended to do this in an empty level)"

**Comment by Its4Nik** [comment]
@SenseiUsagi please provide more Information in Issues, no one really knows what you want to do here....

(I know this is your project but other people might want to contribute and they often look at Issues first because thats what's currently being developed)

**Comment by SenseiUsagi** [comment]
lmao
